---
fig_caption: yes
output:
  html_document:
           self_contained: false
           # theme: null
           css: "https://innoscape.de/pharma_intro/style.css"
           highlight: null
           mathjax: null

resource_files:
- gva_data_ch.fst
runtime: shiny
---

```{r setup, include=FALSE}
library("shiny")
library("ggplot2")
library("RColorBrewer")
library("shinyWidgets")
library("fst")
library("plotly")
```

```{r context="data", echo=FALSE}
# Load data on employment 
gva <- xfun::cache_rds({read.fst("gva_data_ch.fst")})
```




```{r, echo=FALSE}
# Input panels for indicator and industry
radioButtons(inputId = "variable_gva", label = "Choose a variable",
          choices = list("Share in GDP" = "Share in GDP",
                         "GVA in millions CHF" = "GVA in millions CHF", 
                         "GVA percentage change" = "GVA percentage change"),
          selected = "Share in GDP", 
          inline = T)

  pickerInput(inputId = "ind.name_gva",
              label = "Choose industries", 
              choices= sort(unique(gva$ind.name)),
              selected = "Pharmaceutical products",
              options = list(`actions-box` = TRUE),
              multiple = TRUE)

    # subset the data according to the input:
  d_gva <- reactive({ gva %>%
                    filter(variable %in% input$variable_gva,
                           ind.name %in% input$ind.name_gva)
      })
  
renderPlotly({


  
 

if(nrow(d_gva()) != 0){
    # specify y axis title
  Y_AXIS_TITLE <- if(input$variable_gva == "Share in GDP"){"Share in GDP (in %)"}else{
    if(input$variable_gva == "GVA in millions CHF"){"GVA (in millions CHF)"}else{
      "GVA change (in %)"}}
  
# make the plot
  ggplotly(
    ggplot(d_gva(),aes(x = as.numeric(year), y = value, group = ind.name, colour = ind.name, label = Industry)) +
        geom_point(alpha = 0.7) +
            geom_line()+
           scale_color_manual(values = colorRampPalette(brewer.pal(8, "RdBu")[c(1:3, 6:8)])(length(unique(d_gva()$ind.name)))) +
            xlab("Year")+
            ylab(Y_AXIS_TITLE)+
            guides(color = FALSE)+
            scale_x_continuous(breaks = seq(min(d_gva()$year), max(d_gva()$year), by = 5)) +
                 theme(axis.title = element_text(face="bold",size = 10),
                       panel.background = element_blank(),
                       axis.line = element_line(),
                       legend.position="bottom"
                       ), dynamicTicks = T,  tooltip = c("label")) %>%
                          config(displayModeBar = F) %>%
                          layout(xaxis = list(fixedrange=T),
                          yaxis = list(fixedrange=T),
                                 legend = list(orientation = "h", y = -0.25)) %>% 
               partial_bundle()
  
      # plot_ly(d_gva(), x = ~as.numeric(year), y = ~value,
      #                   type = "scatter", mode = 'lines+markers',
      #       color = ~ind.name,
      #       colors = colorRampPalette(brewer.pal(8, "RdBu")[c(1:3, 6:8)])(length(unique(d_gva()$ind.name))),
      #       text = ~Industry,
      #       hoverinfo = 'text') %>%
      #       config(displayModeBar = F) %>%
      #       layout(xaxis = list(title = "<b>Year<b>"), yaxis = list(title = paste0("<b>", Y_AXIS_TITLE, "<b>")), legend = list(x = 0, y = 100, orientation = 'h'))

  
    
  } else{}
  })

```
