```{r, echo=FALSE}


# Input panels for indicator, industry and year

  radioButtons("variable", "Choose a variable",
               choices = list("Values in thousand USD"="val_export", 
                              "% in Destination Exports"="share_in_tot",
                              "% in Industry Exports"="share_in_tot2"),
                                selected = "val_export")

  selectizeInput("ind.code", "Industry", 
                 choices = c(volumes$ind.code),multiple = TRUE, 
                                selected = "21")
  
  sliderInput("year", "Year", min=1990, max=2019, value=2000, sep="")

    
```


```{r, echo=FALSE}

  tradedata <- readRDS("/scicore/home/weder/GROUP/Innovation/02_section_I_data/oecd_trade_final_2020_gps_par_rep_new_final.rds")

# filter the data to leave only Switzerland:
  volumes <- subset(tradedata,rep.code=="CHE")
  volumes <-transform(volumes, year = as.numeric(year)) %>% # Transform to numeric values
            mutate_at(c("lat_par", "long_par", "lat_rep", "long_rep"), as.numeric)

# Create the world map:
  map_world <- map_data(map = "world") %>%
               filter(region != "Antarctica")

  renderPlotly({

# subset the data accoding to the input:
    dr <- reactive({volumes %>%
                    filter(variable %in% input$variable,
                           ind.code %in% input$ind.code,
                           year %in% input$year)
    }) 

# make the plot
  ggplotly(  
            ggplot() +
              geom_polygon(data = map_world,
                           aes(long, lat, group = group, fill = region), 
                           show.legend = FALSE,
                           alpha = 0.25,
                           fill="lightgray",
                           color = "white") +
              geom_curve(data = dr(), 
                         aes(x = long_rep, xend = long_par,
                             y = lat_rep, yend = lat_par),
                         curvature = 0.1, 
                         col="turquoise2", 
                         size = 0.10,
                         alpha = 0.5) +
              geom_point(data = dr(),
                         aes(long_par, lat_par, size = value), color = "chocolate1",alpha = 0.5) +
              theme_bw() +
              theme(axis.line = element_blank(),
                    panel.grid.major = element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.background = element_blank(),
                    panel.border = element_blank(),
                    axis.ticks = element_blank(),
                    axis.title = element_blank(),
                    axis.text = element_blank())
      )
    
  })

```
