```{r, echo=FALSE}


# Input panels for indicator and industry

    radioButtons("variable", "Choose a variable",
          choices = list("GVA in millions CHF"="gva_abs", 
                         "Share in total GVA"="gva_share",
                         "GVA percentage change"="gva_prchange"),
          selected = "gva_share")
          
    selectizeInput("ind.name", "Choose industry",
          choices = c(gva$ind.name),multiple = TRUE, selected = "Manufacture of basic pharmaceutical products and pharmaceutical preparations")
    
```


```{r, echo=FALSE}

  gva <- readRDS("gva_data_ch.rds")

  renderPlotly({

# subset the data accoding to the input:
  dr <- reactive({ gva %>%
                    filter(variable %in% input$variable,
                           ind.name %in% input$ind.name)
      }) 

# make the plot
  ggplotly(  
    ggplot(dr(),aes(x = year, y = value, group = ind.name, colour = ind.name)) +
        geom_line()
      )
    
  })

```
