```{r, echo=FALSE}


# Input panels for indicator and industry

  checkboxGroupInput("variable", "Choose a productivity indicator with:", 
                         choices = list("Only domestic workers"="ilo_prod", 
                                        "Total jobs in firms"="bfs_prod",
                                        "Domestic and cross-border workers"="ilocross_prod"),
                         selected = "ilo_prod")
  selectizeInput("ind.name", "Choose industry",
                         choices = c(labprod$ind.name),multiple = TRUE, selected = "Manufacture of pharmaceutical products")
    
```


```{r, echo=FALSE}

labprod <- readRDS("lab_prod_final_ch.rds")

  renderPlotly({

# subset the data accoding to the input:
  dr <- reactive({labprod %>%
                        filter(variable %in% input$variable,
                               ind.name %in% input$ind.name)
      }) 

# make the plot
  ggplotly(  
           ggplot(dr(),aes(x = year, y = value, group = interaction(ind.name, variable), colour = ind.name,linetype  = variable)) +
           geom_line()
      )
    
  })

```
