---
fig_caption: yes
output:
  html_document:
           self_contained: false
           # theme: null
           css: style.css
           highlight: null
           mathjax: null

resource_files:
- gva_data_ch.fst
runtime: shiny
---

```{r setup, include=FALSE}
library("shiny")
library("ggplot2")
library("RColorBrewer")
library("shinyWidgets")
library("fst")
library("plotly")


```

```{r context="data", echo=FALSE}
# Load data on employment 
labprod <- xfun::cache_rds({read.fst("labprod.fst")})
```

```{r, echo=FALSE}


# Input panels for indicator and industry
  checkboxGroupInput(inputId = "variable_prod", label = "Choose a productivity indicator",
                         choices = list("Only domestic workers"="Only domestic workers",
                                        "Total jobs in firms"="Total jobs in firms",
                                        "Domestic and cross-border workers"="Domestic and cross-border workers"),
                         selected = "Only domestic workers",
                         inline = T)

    # radioButtons("variable_prod", "Choose a productivity indicator with:",
    #                choices = list("Only domestic workers"="Only domestic workers",
    #                               "Total jobs in firms"="Total jobs in firms",
    #                               "Domestic and cross-border workers"="Domestic and cross-border workers"),
    #                      selected = "Only domestic workers",
    #                      inline = TRUE)

  pickerInput(inputId = "ind.name_prod",
              label = "Choose industry", 
              choices= sort(unique(labprod$ind.name)),
              selected = c("Pharmaceutical products"),
              options = list(`actions-box` = TRUE),
              multiple = TRUE)
  
# subset the data according to the input:
  d_output <- reactive({labprod %>%
                        filter(variable %in% input$variable_prod,
                               ind.name %in% input$ind.name_prod)
      })
  
  renderPlotly({


  
if(nrow(d_output()) != 0){
# make the plot
  Y_MAX <- max(d_output()$value, na.rm = TRUE)
  ggplotly(
           ggplot(d_output(),aes(x = as.numeric(year), y = value,
                                 group = interaction(ind.name, variable, sep = ": "),
                                 colour = ind.name, linetype  = variable, label = Industry)) +
           geom_point(alpha = 0.7) +
  scale_color_manual(values = colorRampPalette(brewer.pal(8, "RdBu")[c(1:3, 6:8)])(length(unique(d_output()$ind.name)))) +
            geom_line()+
            xlab("Year")+
            ylab(input$variable_prod)+
            ylim(0, Y_MAX)+
            guides(color = FALSE)+
            scale_x_continuous(breaks = seq(min(d_output()$year), max(d_output()$year), by = 5)) +
            theme(axis.title = element_text(face="bold",size = 10),
                       panel.background = element_blank(),
                       axis.line = element_line()
            ), dynamicTicks = T,  tooltip = c("label")) %>%
                          config(displayModeBar = F) %>%
                          layout(xaxis = list(fixedrange=T),
                          yaxis = list(fixedrange=T),
                                 legend = list(orientation = "h", y = -0.25))
  
  
      # d_output() %>% group_by(interaction(ind.name, input$variable_prod, sep = ": ")) %>% plot_ly(x = ~as.numeric(year), y = ~value,
      #                   type = "scatter", mode = 'lines+markers',
      #       color = ~ind.name,
      #       dash = ~ind.name,
      #       colors = colorRampPalette(brewer.pal(8, "RdBu")[c(1:3, 6:8)])(length(unique(d_output()$ind.name))),
      #       text = ~Industry,
      #       hoverinfo = 'text') %>%
      #       config(displayModeBar = F) %>%
      #       layout(xaxis = list(title = "<b>Year<b>"), yaxis = list(title = paste0("<b>", input$variable_prod, "<b>")), legend = list(x = 0, y = 100, orientation = 'h'))

    
} else{}  
  })


  
```
